# Etapa 2 — Análise Exploratória de Dados

Entrada: os CSVs que a Etapa 1 gravou em `../data/raw/`.
Saída: uma tabela horária limpa em `../data/processed/dataset.csv`, mais os
gráficos e as conclusões que sustentam o que você vai afirmar.

As seções abaixo são um roteiro, não uma receita. Responda as perguntas de
cada uma com código e, no fim, em texto. Acrescente seções se quiser.

In [9]:
from pathlib import Path

DIR_RAW = Path("..") / "data" / "raw"
DIR_PROC = Path("..") / "data" / "processed"
DIR_PROC.mkdir(parents=True, exist_ok=True)

# TODO: imports (pandas, matplotlib, seaborn, ...)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)

## 1. Carregar os CSVs

Leia os quatro arquivos de `../data/raw/`.

- Quantas linhas tem cada um? O número faz sentido para o período coletado?
- Os tipos vieram certos, ou datas e números chegaram como texto?
- Há colunas vazias, ou linhas duplicadas?

In [10]:
mares_csv = "mares_2025.csv"
previsao_csv = "mares_previsao.csv"
ondas_csv = "ondas.csv"
vento_csv = "vento.csv"

df_mares = pd.read_csv(DIR_RAW / mares_csv)
df_previsao = pd.read_csv(DIR_RAW / previsao_csv)
df_ondas = pd.read_csv(DIR_RAW / ondas_csv)
df_vento = pd.read_csv(DIR_RAW / vento_csv)

In [11]:
print("DataFrames carregados com sucesso:")
print(f"- {mares_csv}: {df_mares.shape[0]} linhas, {df_mares.shape[1]} colunas")
print(f"- {previsao_csv}: {df_previsao.shape[0]} linhas, {df_previsao.shape[1]} colunas")
print(f"- {ondas_csv}: {df_ondas.shape[0]} linhas, {df_ondas.shape[1]} colunas")
print(f"- {vento_csv}: {df_vento.shape[0]} linhas, {df_vento.shape[1]} colunas")

DataFrames carregados com sucesso:
- mares_2025.csv: 1410 linhas, 9 colunas
- mares_previsao.csv: 120 linhas, 9 colunas
- ondas.csv: 168 linhas, 6 colunas
- vento.csv: 168 linhas, 6 colunas

In [12]:
df_mares.sample(5)

       ano  mes  dia   hora  altura   tipo  coeficiente nascer_sol por_sol
82    2025    1   22  10:26     1.8   alta           36       5:16   17:45
599   2025    6    5   5:48     0.8  baixa           51       5:25   17:10
1158  2025   10   27  20:07     1.9   alta           41       4:51   17:14
645   2025    6   17   1:50     0.6  baixa           59       5:27   17:12
287   2025    3   16  11:08     0.3  baixa           84       5:22   17:32

In [13]:
df_mares.info()

<class 'pandas.DataFrame'>
RangeIndex: 1410 entries, 0 to 1409
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ano          1410 non-null   int64
 1   mes          1410 non-null   int64
 2   dia          1410 non-null   int64
 3   hora         1410 non-null   str
 4   altura       1410 non-null   float64
 5   tipo         1410 non-null   str
 6   coeficiente  1410 non-null   int64
 7   nascer_sol   1410 non-null   str
 8   por_sol      1410 non-null   str
dtypes: float64(1), int64(4), str(4)
memory usage: 99.3 KB

In [14]:
df_mares.isna().sum()

ano            0
mes            0
dia            0
hora           0
altura         0
tipo           0
coeficiente    0
nascer_sol     0
por_sol        0
dtype: int64

In [15]:
df_mares.duplicated().sum()

np.int64(0)

In [16]:
df_previsao.sample(5)

      ano  mes  dia   hora  altura   tipo  coeficiente nascer_sol por_sol
36   2026   10   10   9:35     0.2  baixa           96       4:58   17:14
14   2026   10    4  16:56     0.8  baixa           44       5:01   17:14
37   2026   10   10  15:39     2.5   alta           96       4:58   17:14
113  2026   10   30   7:37     2.3   alta           64       4:51   17:14
56   2026   10   15  13:21     0.7  baixa           53       4:56   17:13

In [17]:
df_previsao.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ano          120 non-null    int64
 1   mes          120 non-null    int64
 2   dia          120 non-null    int64
 3   hora         120 non-null    str
 4   altura       120 non-null    float64
 5   tipo         120 non-null    str
 6   coeficiente  120 non-null    int64
 7   nascer_sol   120 non-null    str
 8   por_sol      120 non-null    str
dtypes: float64(1), int64(4), str(4)
memory usage: 8.6 KB

In [18]:
df_previsao.isna().sum()

ano            0
mes            0
dia            0
hora           0
altura         0
tipo           0
coeficiente    0
nascer_sol     0
por_sol        0
dtype: int64

In [19]:
df_previsao.duplicated().sum()

np.int64(0)

In [20]:
df_ondas.sample(5)

      ano  mes  dia   hora direcao  altura_onda_m
103  2026   10   15   7:00       E            1.4
32   2026   10   12   8:00       E            1.3
18   2026   10   11  18:00       E            1.0
65   2026   10   13  17:00       E            1.2
37   2026   10   12  13:00       E            1.2

In [21]:
df_ondas.info()

<class 'pandas.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ano            168 non-null    int64
 1   mes            168 non-null    int64
 2   dia            168 non-null    int64
 3   hora           168 non-null    str
 4   direcao        168 non-null    str
 5   altura_onda_m  168 non-null    float64
dtypes: float64(1), int64(3), str(2)
memory usage: 8.0 KB

In [22]:
df_ondas.isna().sum()

ano              0
mes              0
dia              0
hora             0
direcao          0
altura_onda_m    0
dtype: int64

In [23]:
df_ondas.duplicated().sum()

np.int64(0)

In [24]:
df_vento.sample(5)

      ano  mes  dia   hora direcao  velocidade_vento_kmh
64   2026   10   13  16:00     ESE                  21.0
127  2026   10   16   7:00     ENE                  23.0
125  2026   10   16   5:00     ENE                  23.0
137  2026   10   16  17:00     ENE                  19.0
77   2026   10   14   5:00       E                  24.0

In [25]:
df_vento.info()

<class 'pandas.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ano                   168 non-null    int64
 1   mes                   168 non-null    int64
 2   dia                   168 non-null    int64
 3   hora                  168 non-null    str
 4   direcao               168 non-null    str
 5   velocidade_vento_kmh  168 non-null    float64
dtypes: float64(1), int64(3), str(2)
memory usage: 8.0 KB

In [26]:
df_vento.isna().sum()

ano                     0
mes                     0
dia                     0
hora                    0
direcao                 0
velocidade_vento_kmh    0
dtype: int64

In [27]:
df_vento.duplicated().sum()

np.int64(0)

**Conclusões da seção 1**

| Tabela | Linhas | Colunas | Conta |
|---|---|---|---|
| `mares_2025` | 1410 | 9 | 365 dias × ~3,9 marés/dia |
| `mares_previsao` | 120 | 9 | 31 dias (outubro/2026) × ~3,9 marés/dia |
| `ondas` | 168 | 6 | 7 dias × 24 horas |
| `vento` | 168 | 6 | 7 dias × 24 horas |

- **Número de linhas:** os tamanhos fazem sentido. As duas tabelas de maré ficam abaixo de 4 eventos por dia (365 × 4 = 1460 e 31 × 4 = 124) porque o intervalo entre marés é de cerca de 6h12 e, por isso, alguns dias têm só 3 eventos. As tabelas de ondas e vento têm exatamente 24 leituras por dia, nos 7 dias da previsão.
- **Tipos:** `altura`, `altura_onda_m` e `velocidade_vento_kmh` já chegaram como `float64`, então a vírgula decimal foi resolvida na coleta. `hora`, `nascer_sol` e `por_sol` vieram como texto, e a data está dividida em três colunas inteiras (`ano`, `mes`, `dia`). Isso será tratado na limpeza. `direcao` (vento e onda) é categórica, em texto.
- **Nulos e duplicatas:** nenhuma das quatro tabelas tem valores nulos nem linhas duplicadas.
- **Cobertura:** a tábua de 2025 cobre vários meses do ano. As previsões de ondas e vento cobrem só outubro de 2026, então não têm datas em comum com a tábua de 2025.

## 2. Limpeza

Deixe cada tabela num estado em que dá para confiar.

- Datas e horas: viram `datetime`? Vale montar uma coluna única de data + hora?
- Decimais: o site usa vírgula. Isso já foi resolvido na Etapa 1 ou sobrou aqui?
- O que fazer com nulos: descartar a linha, preencher, ou manter e documentar?
- Duplicatas: existem? De onde vieram?

## 3. Explorar cada tabela separadamente

Antes de juntar, entenda cada fonte.

**Marés** — como a altura se distribui entre marés altas e baixas? O
coeficiente varia ao longo do ano com algum padrão? Ele tem relação com a
fase da lua?

**Ondas** — qual a faixa de altura na janela coletada? Há padrão por hora do
dia, ou a variação é só por dia?

**Vento** — quais horas são mais calmas? A direção predominante muda ao longo
do dia? (Vento da terra para o mar e vento do mar para a terra fazem coisas
opostas com a onda.)

Um gráfico por pergunta. Escreva o que você leu nele.

## 4. Juntar as tabelas

Esta é a parte difícil, e ela tem mais de uma resposta certa.

As granularidades não batem: onda e vento são leituras horárias; maré são ~4
eventos por dia (os instantes de máxima e mínima). Para ter uma linha por hora
com as três informações você precisa decidir:

- Como levar a maré para a grade horária? Interpolar entre eventos? Repetir o
  último valor? Guardar apenas se a maré está subindo ou descendo? O que cada
  escolha assume sobre a curva real da maré — e onde essa suposição erra?
- Qual o tipo de junção? A previsão de onda e a de vento cobrem exatamente as
  mesmas horas? Se não, você mantém as horas incompletas ou corta?
- Que variáveis derivadas de tempo ajudam a responder a pergunta do projeto
  (dia da semana, período do dia, ...)?

Justifique as escolhas em markdown. Elas são a base das duas próximas etapas.

## 5. Visualizações voltadas à pergunta

Agora com a tabela junta: quando as condições coincidem?

- As horas de onda maior são as mesmas de vento mais fraco, ou elas se
  desencontram?
- Existe relação visível entre altura da maré e altura da onda?
- Quais dias e horas da janela se destacam?

Prefira poucos gráficos legíveis a muitos gráficos.

## 6. Salvar o dataset processado

Grave o resultado em `../data/processed/dataset.csv`. A Etapa 3 lê esse
arquivo — se as colunas mudarem depois, o notebook de ML muda também.

## 7. Conclusões

Em texto, sem código:

1. O que os dados mostram sobre as condições da janela coletada?
2. Que decisão de limpeza ou de junção você tomou que mais influencia o
   resultado, e por quê?
3. O que esses dados **não** permitem afirmar?